### ISSUE TITLE
Add a little FCP to-do list to the tickyboxes comment

### ISSUE THREAD

**Issue by anoadragon453** [matrix-org/mscbot-python#33]
To transparently tell people what exactly needs to happen in order for FCP to start. The checklist would be slightly different depending on the FCP disposition (merge, close, postpone). For merge, you would have something like:

- [ ] This MSC has one or more implementation(s), or does not need one.
- [ ] There are no open concerns.
- [ ] At least 75% of the Spec Core Team members have approved this MSC.

Existing FCP comments can be updated with this list when they are edited.

**Comment by kegsay** [comment]
I would add to this:
 - [ ] If this MSC touches [sensitive parts of the specification](https://github.com/matrix-org/matrix-spec-proposals/blob/kegan/complement-msc/proposals/4092-enforce-tests.md#proposal) they have tests to assert correctness.
 - [ ] If this MSC depends on another MSC, or is depended on by another MSC, both MSCs are ready to merge.

**Comment by anoadragon453** [comment]
@kegsay Those are probably better added to: https://github.com/matrix-org/matrix-spec-proposals/blob/main/MSC_CHECKLIST.md
